#! /usr/bin/python
# -*-coding:utf-8 -*

from os import geteuid
from sys import argv, exit
from subprocess import check_output
import getopt

from album.snap_and_roll import make_snap, prompt_rollback 
from album.snapshots import print_snapshots_list, prompt_delete_snapshots

def usage():
	print("usage: ", argv[0], "actions")
	print("actions:")
	print("   -s, --snap       Create a snapshot of the current system")
	print("   -r, --rollback   Roll back the main system into the state of the current snapshot state")
	print("   -l, --list       List available snapshots")
	print("   -d, --delete     Choose snapshots to delete") 
	print("   -h, --help       This message")

def is_root():
	if geteuid() == 0:
		return True
	else:
		return False

def is_btrfs():
	fs = str(check_output(["grub-probe", "--target=fs", "/"]), "utf-8").strip("\n")
	if fs == "btrfs":
		return True
	else:
		return False

def main(argv):
	try:
		opts, args = getopt.gnu_getopt(argv, "hsrld", ["help", "snapshot", "rollback", "list", "delete"])
	except getopt.GetoptError:
		usage()
		exit(2)
	if opts == []:
		usage()
		exit(2)
	for opt, arg in opts:
		if opt in ("-h", "--help"):
			usage()
			exit(0)
		if opt in ("-s", "--snapshot"):
			make_snap()
		if opt in ("-r", "--rollback"):
			prompt_rollback()
		if opt in ("-l", "--list"):
			print_snapshots_list()
		if opt in ("-d", "--delete"):
			print_snapshots_list()
			prompt_delete_snapshots()


if __name__ == "__main__":
	if is_root() is True:
		if is_btrfs() is True:
			main(argv[1:])
		else:
			print("This program supports only root filesystem in a btrfs partition.")
			exit(1)
	else:
		print("You must be root to run this program.")
		exit(1)

